# -*- coding: utf-8 -*-
"""DEEP Learning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SsGQ0IHjnfh6qqUaGMvAwqRHmjDJfLFp

**DATA PREPARATION AND SCALING**
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

train_data_path = "/content/DailyDelhiClimateTrain.csv"
test_data_path = "/content/DailyDelhiClimateTest.csv"

train_df = pd.read_csv(train_data_path)
test_df = pd.read_csv(test_data_path)

# Parse dates and set index
train_df['date'] = pd.to_datetime(train_df['date'])
test_df['date'] = pd.to_datetime(test_df['date'])
train_df.set_index('date', inplace=True)
test_df.set_index('date', inplace=True)

from sklearn.preprocessing import StandardScaler
import numpy as np

# Combine train and test for consistent scaling
combined_df = pd.concat([train_df, test_df])

# Normalize the data using StandardScaler
scaler = StandardScaler()
scaled_data = scaler.fit_transform(combined_df)

# Split the data back into train and test
train_size = len(train_df)
train_data = scaled_data[:train_size]
test_data = scaled_data[train_size:]

print(f"Train dataset size: {train_df.shape}")
print(f"Test dataset size: {test_df.shape}")

sequence_length = 30

def create_sequences(data, sequence_length):
    X, y = [], []
    for i in range(len(data) - sequence_length):
        X.append(data[i:i + sequence_length])
        y.append(data[i + sequence_length, 0])  # Assuming we want to predict the first feature (e.g., temperature)
    return np.array(X), np.array(y)


# Create sequences for training and testing
X_train, y_train = create_sequences(train_data, sequence_length)
X_test, y_test = create_sequences(test_data, sequence_length)

# Check shapes
print(f"Train shape: X={X_train.shape}, y={y_train.shape}")
print(f"Test shape: X={X_test.shape}, y={y_test.shape}")

"""**LSTM MODEL**"""

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

# LSTM model definition
def create_lstm_model(input_shape):
    model = Sequential([
        LSTM(128, return_sequences=True, input_shape=input_shape),
        Dropout(0.2),
        LSTM(64),
        Dropout(0.2),
        Dense(1)  # Predicting a single value per sequence
    ])
    model.compile(optimizer='adam', loss='mse', metrics=['mae'])
    return model

lstm_model = create_lstm_model((X_train.shape[1], X_train.shape[2]))
lstm_model.summary()

# Train the LSTM model
history_lstm = lstm_model.fit(X_train, y_train, epochs=50, batch_size=32, validation_data=(X_test, y_test))

"""**TRANSFORMER**"""

from tensorflow.keras.layers import Input, MultiHeadAttention, LayerNormalization, Dense, Dropout, Add
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Lambda
from tensorflow.keras.layers import Embedding

def transformer_block(inputs, num_heads=4, ff_dim=32, dropout_rate=0.1):
    attention_output = MultiHeadAttention(num_heads=num_heads, key_dim=ff_dim)(inputs, inputs)
    attention_output = Dropout(dropout_rate)(attention_output)
    attention_output = LayerNormalization(epsilon=1e-6)(inputs + attention_output)

    ff_output = Dense(ff_dim, activation='relu')(attention_output)
    ff_output = Dropout(dropout_rate)(ff_output)
    ff_output = Dense(inputs.shape[-1])(ff_output)
    ff_output = LayerNormalization(epsilon=1e-6)(attention_output + ff_output)

    return ff_output

# Transformer model definition
def build_transformer_model(sequence_length, num_features):
    inputs = Input(shape=(sequence_length, num_features))
    x = transformer_block(inputs)  # Apply transformer block
    x = transformer_block(x)  # Apply another transformer block
    x = Lambda(lambda t: t[:, -1, :])(x)  # Use the last time step
    outputs = Dense(1)(x)  # Predict a single value
    model = Model(inputs, outputs)
    model.compile(optimizer='adam', loss='mse', metrics=['mae'])
    return model

transformer_model = build_transformer_model(sequence_length, X_train.shape[2])
transformer_model.summary()

# Train the Transformer model
history_transformer = transformer_model.fit(X_train, y_train, epochs=50, batch_size=32, validation_data=(X_test, y_test))

"""**HYPERPARAMETER TUNING**"""

pip install optuna

import optuna
from keras.optimizers import Adam

def objective(trial):
    units = trial.suggest_int('units', 32, 256)
    learning_rate = trial.suggest_loguniform('lr', 1e-4, 1e-2)
    dropout_rate = trial.suggest_uniform('dropout', 0.1, 0.5)

    model = Sequential([
        LSTM(units, return_sequences=True, input_shape=(X_train.shape[1], X_train.shape[2])),
        Dropout(dropout_rate),
        Dense(1)
    ])
    model.compile(optimizer=Adam(learning_rate=learning_rate), loss='mse')
    history = model.fit(X_train, y_train, epochs=10, validation_split=0.2)
    return history.history['val_loss'][-1]

study = optuna.create_study(direction='minimize')
study.optimize(objective, n_trials=10)

"""**MODEL EVALUATION**"""

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

# Evaluate LSTM
lstm_predictions = lstm_model.predict(X_test)
lstm_rmse = np.sqrt(mean_squared_error(y_test, lstm_predictions))
lstm_mae = mean_absolute_error(y_test, lstm_predictions)
lstm_r2 = r2_score(y_test, lstm_predictions)
print(f"LSTM - RMSE: {lstm_rmse}, MAE: {lstm_mae}, R²: {lstm_r2}")

# Evaluate Transformer
transformer_predictions = transformer_model.predict(X_test)
transformer_rmse = np.sqrt(mean_squared_error(y_test, transformer_predictions))
transformer_mae = mean_absolute_error(y_test, transformer_predictions)
transformer_r2 = r2_score(y_test, transformer_predictions)
print(f"Transformer - RMSE: {transformer_rmse}, MAE: {transformer_mae}, R²: {transformer_r2}")

"""## **ENHANCED TRANSFORMER MODEL**"""

import numpy as np
from tensorflow.keras.layers import Layer
import tensorflow as tf

# Positional encoding layer
class PositionalEncoding(Layer):
    def __init__(self, max_len, d_model):
        super().__init__()
        self.pos_encoding = self.positional_encoding(max_len, d_model)

    def positional_encoding(self, max_len, d_model):
        angle_rads = self.get_angles(
            np.arange(max_len)[:, np.newaxis],
            np.arange(d_model)[np.newaxis, :],
            d_model,
        )
        angle_rads[:, 0::2] = np.sin(angle_rads[:, 0::2])
        angle_rads[:, 1::2] = np.cos(angle_rads[:, 1::2])
        return tf.cast(angle_rads[np.newaxis, ...], dtype=tf.float32)

    def get_angles(self, pos, i, d_model):
        angle_rates = 1 / np.power(10000, (2 * (i // 2)) / np.float32(d_model))
        return pos * angle_rates

    def call(self, inputs):
        return inputs + self.pos_encoding[:, : tf.shape(inputs)[1], :]

# Enhanced Transformer model
def build_enhanced_transformer(sequence_length, num_features, num_heads=4, ff_dim=64):
    inputs = Input(shape=(sequence_length, num_features))
    x = PositionalEncoding(sequence_length, num_features)(inputs)
    x = transformer_block(x, num_heads=num_heads, ff_dim=ff_dim, dropout_rate=0.2)
    x = transformer_block(x, num_heads=num_heads, ff_dim=ff_dim, dropout_rate=0.2)
    x = Lambda(lambda t: t[:, -1, :])(x)  # Use the last time step
    outputs = Dense(1)(x)  # Predict a single value
    model = Model(inputs, outputs)
    model.compile(optimizer='adam', loss='mse', metrics=['mae'])
    return model

# Build and train the enhanced Transformer model
enhanced_transformer_model = build_enhanced_transformer(sequence_length, X_train.shape[2], num_heads=8, ff_dim=128)
enhanced_transformer_model.summary()

history_enhanced_transformer = enhanced_transformer_model.fit(
    X_train, y_train, epochs=50, batch_size=32, validation_data=(X_test, y_test)
)

"""## **ENHANCED LSTM MODEL**"""

from tensorflow.keras.layers import Bidirectional

# Enhanced LSTM model
def create_enhanced_lstm_model(input_shape):
    model = Sequential([
        Bidirectional(LSTM(128, return_sequences=True), input_shape=input_shape),
        Dropout(0.3),
        LSTM(64, return_sequences=False),
        Dropout(0.3),
        Dense(1)
    ])
    model.compile(optimizer=Adam(learning_rate=0.001), loss='mse', metrics=['mae'])
    return model

enhanced_lstm_model = create_enhanced_lstm_model((X_train.shape[1], X_train.shape[2]))
enhanced_lstm_model.summary()

history_enhanced_lstm = enhanced_lstm_model.fit(
    X_train, y_train, epochs=50, batch_size=32, validation_data=(X_test, y_test)
)

"""## **Advanced Hyperparameter Optimization**"""

def transformer_objective(trial):
    num_heads = trial.suggest_int("num_heads", 2, 8)
    ff_dim = trial.suggest_int("ff_dim", 32, 256)
    dropout_rate = trial.suggest_float("dropout_rate", 0.1, 0.5)
    learning_rate = trial.suggest_float("learning_rate", 1e-4, 1e-2)

    model = build_enhanced_transformer(sequence_length, X_train.shape[2], num_heads, ff_dim)
    model.compile(optimizer=Adam(learning_rate=learning_rate), loss='mse', metrics=['mae'])
    history = model.fit(X_train, y_train, epochs=10, validation_split=0.2, verbose=0)
    return history.history['val_loss'][-1]

study = optuna.create_study(direction="minimize")
study.optimize(transformer_objective, n_trials=20)
best_params = study.best_params

print("Best Transformer Params:", best_params)

"""### **REGULARIZATION**"""

from tensorflow.keras.callbacks import ReduceLROnPlateau

reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=5, min_lr=1e-6)

enhanced_transformer_model.fit(
    X_train, y_train, epochs=50, batch_size=32, validation_data=(X_test, y_test), callbacks=[reduce_lr]
)

"""## **METRICS EVALUATION**"""

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

# Evaluate LSTM model
lstm_predictions = enhanced_lstm_model.predict(X_test)
lstm_rmse = np.sqrt(mean_squared_error(y_test, lstm_predictions))
lstm_mae = mean_absolute_error(y_test, lstm_predictions)
lstm_r2 = r2_score(y_test, lstm_predictions)
print(f"LSTM - RMSE: {lstm_rmse:.4f}, MAE: {lstm_mae:.4f}, R²: {lstm_r2:.4f}")

# Evaluate Transformer model
transformer_predictions = enhanced_transformer_model.predict(X_test)
transformer_rmse = np.sqrt(mean_squared_error(y_test, transformer_predictions))
transformer_mae = mean_absolute_error(y_test, transformer_predictions)
transformer_r2 = r2_score(y_test, transformer_predictions)
print(f"Transformer - RMSE: {transformer_rmse:.4f}, MAE: {transformer_mae:.4f}, R²: {transformer_r2:.4f}")

"""## **ENSEMBLE MODEL**"""

def optimize_ensemble_weights(trial):
    lstm_weight = trial.suggest_uniform("lstm_weight", 0, 1)
    ensemble_predictions = (
        lstm_weight * lstm_predictions + (1 - lstm_weight) * transformer_predictions
    )
    return np.sqrt(mean_squared_error(y_test, ensemble_predictions))

study = optuna.create_study(direction="minimize")
study.optimize(optimize_ensemble_weights, n_trials=10)
best_lstm_weight = study.best_params["lstm_weight"]
best_transformer_weight = 1 - best_lstm_weight

ensemble_predictions = (best_lstm_weight * lstm_predictions + best_transformer_weight * transformer_predictions)

# Evaluate Ensemble
ensemble_rmse = np.sqrt(mean_squared_error(y_test, ensemble_predictions))
ensemble_mae = mean_absolute_error(y_test, ensemble_predictions)
ensemble_r2 = r2_score(y_test, ensemble_predictions)

print(f"Ensemble - RMSE: {ensemble_rmse}, MAE: {ensemble_mae}, R²: {ensemble_r2}")

import matplotlib.pyplot as plt

plt.figure(figsize=(12, 6))

# LSTM Predictions
plt.subplot(1, 3, 1)
plt.plot(y_test, label='Actual')
plt.plot(lstm_predictions, label='LSTM Predicted')
plt.title('LSTM Predictions')
plt.xlabel('Time Steps')
plt.ylabel('Value')
plt.legend()

# Transformer Predictions
plt.subplot(1, 3, 2)
plt.plot(y_test, label='Actual')
plt.plot(transformer_predictions, label='Transformer Predicted')
plt.title('Transformer Predictions')
plt.xlabel('Time Steps')
plt.ylabel('Value')
plt.legend()

# Ensemble Predictions
plt.subplot(1, 3, 3)
plt.plot(y_test, label='Actual')
plt.plot(ensemble_predictions, label='Ensemble Predicted')
plt.title('Ensemble Predictions')
plt.xlabel('Time Steps')
plt.ylabel('Value')
plt.legend()

plt.tight_layout()
plt.show()